// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "prisma generate && ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Solo para verificaciones (migrate diff --from-migrations) — opcional.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
