apiVersion: v1
kind: Secret
metadata:
  name: ef-secrets
  namespace: ef-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me-in-production"
  JWT_SECRET: "change-me-in-production"
  MONGO_PASSWORD: "change-me-in-production"
